#!/bin/sh
if [ $# -lt 1 ];
then
    echo "Usage: $0 <Project Name>"
    exit 1
fi
PROJECT_NAME=$1
C_Q_S_URL="https://github.com/ksrijith/covalent-quickstart.git"
git clone "$C_Q_S_URL" $PROJECT_NAME
cd $PROJECT_NAME
yarn install
./node_modules/.bin/webdriver-manager update
rm -rf .git
git init